//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_items
    {
        public int cart_items_id { get; set; }
        public int cart_id { get; set; }
        public int prod_id { get; set; }
        public string item_name { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    }
}
