//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class order
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int order_id { get; set; }
        public int user_id { get; set; }
        public int cart_id { get; set; }

        [Required(ErrorMessage = "Payment Type is required.")]
        public string paym_type { get; set; }
        public decimal grand_total { get; set; }

        [Required(ErrorMessage = "Mobile Number is required.")]
        public string mobile_num { get; set; }

        [Required(ErrorMessage = "Address is required.")]
        public string address { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual order order1 { get; set; }
        public virtual order order2 { get; set; }
        public virtual user user { get; set; }
    }
}
