//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public int user_id { get; set; }
        public int coup_id { get; set; }
        public int cart_id { get; set; }
        public string paym_type { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime del_date { get; set; }
        public decimal grant_total { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual order order1 { get; set; }
        public virtual order order2 { get; set; }
        public virtual user user { get; set; }
    }
}
