//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> coup_id { get; set; }
        public Nullable<int> event_id { get; set; }
        public string paym_type { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> del_date { get; set; }
        public string del_add { get; set; }
        public Nullable<int> grand_total { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual coupon coupon { get; set; }
        public virtual @event @event { get; set; }
        public virtual user user { get; set; }
    }
}
