//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_items = new HashSet<cart_items>();
        }
    
        public int prod_id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string prod_name { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> price { get; set; }
        public string color { get; set; }
        public byte[] prod_image { get; set; }
        public string prod_desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual category category { get; set; }
    }
}
